version: "3.7"

networks:
  # traefik_net:
  #   name: traefik_net
  keycloak_net:
    name: keycloak_net
  wpf_net:
    name: wpf_net

## Persistent keycloak database
volumes:
  keycloak_db_vol0:
    driver: local
  wpf_db_vol0:
    driver: local

services:
  ##############################################
  ##############################################
  ##
  ## KEYCLOAK-DB
  ## MySQL database to persist the IDP data
  ##
  ##############################################
  ##############################################

  keycloak-db:
    image: mysql:5.7
    container_name: keycloak-db
    env_file: ./keycloak-db.env
    volumes:
      - keycloak_db_vol0:/var/lib/mysql
    networks:
      - keycloak_net
    # labels:
    #   - "traefik.enable=false"

  #########################################################
  #########################################################
  ##
  ## KEYCLOAK
  ## Identity provider
  ## Latest Official Image
  ##
  #########################################################
  #########################################################

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    hostname: keycloak
    domainname: docker.localhost
    env_file: ./keycloak.env
    volumes:
      # Realm configuration file for import
      - "./export/hsa-realm.json:/opt/jboss/keycloak/imports/hsa-realm.json:ro"
    networks:
      - keycloak_net
      # - traefik_net
    # For usage without traefik
    ports:
      # HTTP port
      - 8080:8080
      # HTTPS port
      - 8443:8443
    # labels:
      # Enable this container to be mapped by traefik
      # For more information, see: https://docs.traefik.io/providers/docker/#exposedbydefault
      # - "traefik.enable=true"
      # - "traefik.docker.network=traefik_net"
      # URL to reach this container
      # - "traefik.http.routers.keycloak.rule=Host(`docker.localhost`)"
      # Activation of TLS
      # Access via HTTPS only
      # - "traefik.http.routers.keycloak.entrypoints=websecure"
      # - "traefik.http.routers.keycloak.tls=true"
      # If port is different than 80, use the following service:
      # - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
    depends_on:
      - keycloak-db

  ##############################################
  ##############################################
  ##
  ## WPF-DB
  ## MySQL database to persist the IDP data
  ##
  ##############################################
  ##############################################

  wpf-db:
    image: mysql:5.7
    container_name: wpf-db
    env_file: ./wpf-db.env
    ports:
      - "3307:3307"
    volumes:
      - wpf_db_vol0:/var/lib/mysql
      - "./init_wpf.sql:/docker-entrypoint-initdb.d/init.sql"
    #networks:
    #  - wpf_net
    # labels:
      #   - "traefik.enable=false"


  wpf-backend:
    image: dominikhrn/subject-registration:sha-2bb0287
    container_name: wpf-backend
    ports:
      - "9090:9090"
    depends_on:
      - wpf-db
      - keycloak
