version: "3.7"

## Persistent keycloak database
volumes:
  keycloak_db_vol0:
    driver: local
  wpf_db_vol0:
    driver: local

services:

  ##############################################
  ##############################################
  ##
  ## KEYCLOAK-DB
  ## MySQL database to persist the IDP data
  ##
  ##############################################
  ##############################################
  keycloak-db:
    image: mysql:5.7
    container_name: keycloak-db
    restart: always
    env_file: keycloak/keycloak-db.env
    volumes:
      - keycloak_db_vol0:/var/lib/mysql

  #########################################################
  #########################################################
  ##
  ## KEYCLOAK
  ## Identity provider
  ## Latest Official Image
  ##
  #########################################################
  #########################################################
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    env_file: keycloak/keycloak.env
    volumes:
      # Realm configuration file for import
      - "./keycloak/import/hsa-realm.json:/opt/jboss/keycloak/imports/hsa-realm.json:ro"
    depends_on:
      - keycloak-db

  ##############################################
  ##############################################
  ##
  ## WPF-DB
  ## MySQL database to persist the IDP data
  ##
  ##############################################
  ##############################################
  wpf-db:
    image: mysql:5.7
    container_name: wpf-db
    restart: always
    env_file: wpf/wpf-db.env
    ports:
      - 3307:3306
    volumes:
      - wpf_db_vol0:/var/lib/mysql
      - "./wpf/init_wpf.sql:/docker-entrypoint-initdb.d/init.sql"

  ##############################################
  ##############################################
  ##
  ## WPF-Backend
  ## Subject-Registration spring boot app
  ##
  ##############################################
  ##############################################
  wpf-backend:
    image: dominikhrn/subject-registration:feat-authconverter
    restart: always
    container_name: wpf-backend
    depends_on:
      - wpf-db

  ##############################################
  ##############################################
  ##
  ## WPF-Frontend
  ## Subject-Registration react app
  ##
  ##############################################
  ##############################################
  wpf-frontend:
    image: dominikhrn/subject-registration-frontend:feat-dockerhub
    restart: always
    container_name: wpf-frontend
    depends_on:
      - wpf-db

  ##############################################
  ##############################################
  ##
  ## Proxy
  ## NGINX Proxy
  ##
  ##############################################
  ##############################################
  nginx:
    image: nginx:1.19.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf