version: "3.7"

# networks:
#   traefik_public:
#     name: traefik_public
#   sso_net:
#     internal: true
#     name: sso_net
#   wpf_net:
#     internal: true
#     name: wpf_net

## Persistent keycloak database
volumes:
  keycloak_db_vol0:
    driver: local
  wpf_db_vol0:
    driver: local

services:
  ##############################################
  ##############################################
  ##
  ## KEYCLOAK-DB
  ## MySQL database to persist the IDP data
  ##
  ##############################################
  ##############################################

  keycloak-db:
    image: mysql:5.7
    container_name: keycloak-db
    restart: always
    env_file: ./keycloak/keycloak-db.env
    volumes:
      - keycloak_db_vol0:/var/lib/mysql
    # networks:
    #   - sso_net
    # labels:
    #   - "traefik.enable=false"

  #########################################################
  #########################################################
  ##
  ## KEYCLOAK
  ## Identity provider
  ## Latest Official Image
  ##
  #########################################################
  #########################################################

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    restart: always
    env_file: ./keycloak/keycloak.env
    volumes:
      # Realm configuration file for import
      - "./keycloak/import/hsa-realm.json:/opt/jboss/keycloak/imports/hsa-realm.json:ro"
    # networks:
    #   - sso_net
    #   - traefik_public
    #   - wpf_net
    # For usage without traefik
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.keycloak.rule=Host(`${HOSTNAME}`) && PathPrefix(`/auth`)"
    #   - "traefik.http.routers.keycloak.entrypoints=websecure"
    #   - 'traefik.http.services.keycloak.loadbalancer.server.port=8443'
    depends_on:
      - keycloak-db


  #########################################################
  #########################################################
  ##
  ## Traefik
  ##
  #########################################################
  #########################################################
  # traefik:
  #   container_name: traefik
  #   image: traefik:v2.5.4
  #   env_file: ./traefik/traefik.env
  #   restart: unless-stopped
  #   ports:
  #     - 80:80 # HTTP
  #     - 443:443 # HTTPS
  #     - 10080:10080 # DASHBOARD
  #   networks:
  #     - traefik_public
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./traefik/traefik.yml:/etc/traefik/traefik.yml
  #     - ./traefik/dynamic_config.yml:/etc/traefik/config.yml:ro
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.traefik.rule=Host(`${HOSTNAME}`) && PathPrefix(`/traefik`)"
  #     - "traefik.http.routers.traefik.middlewares=keycloak@file"  # protect Web UI access
  #     - "traefik.http.services.traefik.loadbalancer.server.port=10080"

  ##############################################
  ##############################################
  ##
  ## WPF-DB
  ## MySQL database to persist the IDP data
  ##
  ##############################################
  ##############################################
  wpf-db:
    image: mysql:5.7
    container_name: wpf-db
    restart: always
    env_file: ./wpf/wpf-db.env
    # networks:
    #   - wpf_net
    ports:
      - 3307:3306
    volumes:
      - wpf_db_vol0:/var/lib/mysql
      - "./wpf/init_wpf.sql:/docker-entrypoint-initdb.d/init.sql"

  wpf-backend:
    image: dominikhrn/subject-registration:feat-authconverter
    restart: always
    container_name: wpf-backend
    depends_on:
      - wpf-db
    # networks:
    #   - wpf_net

  wpf-frontend:
    image: dominikhrn/subject-registration-frontend:feat-dockerhub
    restart: always
    container_name: wpf-frontend
    depends_on:
      - wpf-db
    # networks:
    #   - wpf_net

  nginx:
    image: nginx:1.19.1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:8080"
    # networks:
    #   - wpf_net