name: "Test Frontend"

# For now we test the frontend by just building it, in the future tests should be run here

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'
    paths:
      - 'frontend/**'
  pull_request:
    branches:
      - 'master'

  workflow_dispatch:

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
          registry-url: 'https://npm.pkg.github.com'
          scope: '@flowsquad'

      # Should actually be run without scripts, see https://github.com/actions/setup-node ("Use private packages").
      # However, yarn does not allow to run them in a separate step.
      - name: Install Dependencies
        run: npm ci --no-optional
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_DEPLOYMENT_TOKEN }}

      - name: Build Application
        run: npm run build
        env:
          CI: false
